Symfony\Component\Routing\Route:
    type: mappedSuperclass
    fields:
        host:
            type: string
            nullable: true
        schemes:
            type: json_array
            nullable: true
        methods:
            type: json_array
            nullable: true
        defaults:
            type: json_array
            nullable: true
        requirements:
            type: json_array
            nullable: true
        options:
            type: json_array
            nullable: true
