services:
    orm_routing.auto.defunct_route_handler.remove:
        class: Symfony\Cmf\Component\RoutingAuto\DefunctRouteHandler\RemoveDefunctRouteHandler
        arguments:
            - "@orm_routing.auto.adapter"
        tags:
            - name: orm_routing.auto.defunct_route_handler
              alias: remove

    orm_routing.auto.defunct_route_handler.leave_redirect:
        class: Symfony\Cmf\Component\RoutingAuto\DefunctRouteHandler\LeaveRedirectDefunctRouteHandler
        arguments:
            - "@orm_routing.auto.adapter"
        tags:
            - name: orm_routing.auto.defunct_route_handler
              alias: leave_redirect

    orm_routing.auto.defunct_route_handler.delegating:
        class: Symfony\Cmf\Component\RoutingAuto\DefunctRouteHandler\DelegatingDefunctRouteHandler
        arguments:
            - "@orm_routing.auto.metadata.factory"
            - "@orm_routing.auto.adapter"
            - "@orm_routing.auto.service_registry"
