services:
    orm_routing.enhancer.route_content:
        class: Symfony\Cmf\Component\Routing\Enhancer\RouteContentEnhancer
        arguments:
            - _route_object
            - _content
        tags:
            - name: dynamic_router_route_enhancer
              priority: 100

    orm_routing.enhancer.default_controller:
        class: Symfony\Cmf\Component\Routing\Enhancer\FieldPresenceEnhancer
        public: false
        arguments:
            - null
            - _controller
            - "%orm_routing.default_controller%"

    orm_routing.enhancer.explicit_template:
        class: Symfony\Cmf\Component\Routing\Enhancer\FieldPresenceEnhancer
        public: false
        arguments:
            - _template
            - _controller
            - "%orm_routing.default_controller%"

    orm_routing.enhancer.controllers_by_type:
        class: Symfony\Cmf\Component\Routing\Enhancer\FieldMapEnhancer
        public: false
        arguments:
            - type
            - _controller
            - "%orm_routing.controllers_by_type%"

    orm_routing.enhancer.controllers_by_class:
        class: Symfony\Cmf\Component\Routing\Enhancer\FieldByClassEnhancer
        public: false
        arguments:
            - _content
            - _controller
            - "%orm_routing.controllers_by_class%"

    orm_routing.enhancer.controller_for_templates_by_class:
        class: Symfony\Cmf\Component\Routing\Enhancer\FieldByClassEnhancer
        public: false
        arguments:
            - _content
            - _controller
            - {}

    orm_routing.enhancer.templates_by_class:
        class: Symfony\Cmf\Component\Routing\Enhancer\FieldByClassEnhancer
        public: false
        arguments:
            - _content
            - _template
            - "%orm_routing.templates_by_class%"

    orm_routing.enhancer.content_repository:
        class: Symfony\Cmf\Component\Routing\Enhancer\ContentRepositoryEnhancer
        public: false
        arguments:
            - "@orm_routing.content_repository"

    orm_routing.enhancer.orm_content_repository:
        class: SymfonyContrib\Bundle\OrmRoutingBundle\Enhancer\OrmContentRepositoryEnhancer
        public: false
        arguments:
            - "@orm_routing.content_repository"
        tags:
            - name: dynamic_router_route_enhancer
              priority: 200

    orm_routing.dynamic_router:
        class: SymfonyContrib\Bundle\OrmRoutingBundle\Routing\DynamicRouter
        arguments:
            - "@router.request_context"
            - "@orm_routing.nested_matcher"
            - null
            - "%orm_routing.uri_filter_regexp%"
            - "@?event_dispatcher"
            - "@orm_routing.route_provider"
        calls:
            - [setRequest, ["@?request"]]

    orm_routing.nested_matcher:
        class: Symfony\Cmf\Component\Routing\NestedMatcher\NestedMatcher
        arguments:
            - "@orm_routing.route_provider"
            - "@orm_routing.final_matcher"

    orm_routing.matcher.dummy_collection:
        class: Symfony\Component\Routing\RouteCollection
        public: false

    orm_routing.matcher.dummy_context:
        class: Symfony\Component\Routing\RequestContext
        public: false

    orm_routing.final_matcher:
        class: Symfony\Cmf\Component\Routing\NestedMatcher\UrlMatcher
        arguments:
            - "@orm_routing.matcher.dummy_collection"
            - "@orm_routing.matcher.dummy_context"

    orm_routing.generator:
        class: Symfony\Cmf\Component\Routing\ContentAwareGenerator
        arguments:
            - "@orm_routing.route_provider"
            - "@?logger"
